# Generated by Django 4.2.7 on 2025-11-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Person's full name", max_length=200),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Person's email address (must be unique)",
                        max_length=254,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["email"], name="people_pers_email_52ffb2_idx"),
                    models.Index(fields=["name"], name="people_pers_name_3035d1_idx"),
                ],
            },
        ),
    ]
