# Generated by Django 4.2.7 on 2025-11-09 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Person's primary email address (optional)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PersonEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address (must be unique across all people)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary email for this person",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person this email belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person Email",
                "verbose_name_plural": "Person Emails",
                "ordering": ["-is_primary", "email"],
                "indexes": [
                    models.Index(fields=["email"], name="people_pers_email_664b97_idx"),
                    models.Index(
                        fields=["person", "is_primary"],
                        name="people_pers_person__7bb64e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="personemail",
            constraint=models.UniqueConstraint(
                fields=("person", "email"), name="unique_person_email"
            ),
        ),
    ]
