# Generated by Django 4.2.7 on 2025-11-08 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("initiatives", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full organizational group name", max_length=200
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Abbreviated organizational group name", max_length=50
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Organizational group website URL (optional)",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("research", "Research"), ("extension", "Extension")],
                        help_text="Organizational group type (Research or Extension)",
                        max_length=20,
                    ),
                ),
                (
                    "knowledge_area",
                    models.CharField(
                        help_text="Field of study or research domain", max_length=200
                    ),
                ),
                (
                    "campus",
                    models.CharField(
                        help_text="University campus affiliation", max_length=200
                    ),
                ),
                (
                    "initiatives",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Initiatives associated with the organizational group",
                        related_name="groups",
                        to="initiatives.initiative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Group",
                "verbose_name_plural": "Organizational Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationalGroupLeadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Date when leadership began"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when leadership ended (null if ongoing)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this is an active leadership"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Organizational group being led",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizational_group.organizationalgroup",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person who is a leader",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Group Leadership",
                "verbose_name_plural": "Organizational Group Leaderships",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="organizationalgroup",
            name="leaders",
            field=models.ManyToManyField(
                help_text="People who lead the organizational group",
                related_name="led_groups",
                through="organizational_group.OrganizationalGroupLeadership",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="organizationalgroup",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="People who are members of the organizational group",
                related_name="member_groups",
                to="people.person",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalgroupleadership",
            index=models.Index(
                fields=["group", "is_active"], name="organizatio_group_i_ce9f60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalgroupleadership",
            index=models.Index(
                fields=["person"], name="organizatio_person__332daf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalgroupleadership",
            index=models.Index(
                fields=["start_date"], name="organizatio_start_d_dff27c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationalgroupleadership",
            constraint=models.UniqueConstraint(
                fields=("group", "person", "start_date"),
                name="unique_group_person_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationalgroupleadership",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__gte", models.F("start_date")),
                    ("end_date__isnull", True),
                    _connector="OR",
                ),
                name="end_date_after_start_date_leadership",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalgroup",
            index=models.Index(fields=["name"], name="organizatio_name_b0c5b6_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationalgroup",
            index=models.Index(
                fields=["short_name"], name="organizatio_short_n_aabb67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalgroup",
            index=models.Index(fields=["type"], name="organizatio_type_713f85_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationalgroup",
            index=models.Index(fields=["campus"], name="organizatio_campus_ae3223_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationalgroup",
            index=models.Index(
                fields=["knowledge_area"], name="organizatio_knowled_0aafb0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationalgroup",
            constraint=models.UniqueConstraint(
                fields=("short_name", "campus"), name="unique_short_name_campus"
            ),
        ),
    ]
