# Generated by Django 4.2.7 on 2025-11-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full campus name", max_length=200),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short campus code/identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location or address",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campus",
                "verbose_name_plural": "Campuses",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="organizatio_name_fb6bce_idx"),
                    models.Index(fields=["code"], name="organizatio_code_51e82f_idx"),
                ],
            },
        ),
    ]
