# Generated by Django 4.2.7 on 2025-11-09 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0002_campus"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationalgroup",
            name="campus_id",
            field=models.ForeignKey(
                blank=True,
                help_text="University campus affiliation (foreign key)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="organizational_group.campus",
            ),
        ),
    ]
