# Generated by Django 4.2.7 on 2025-11-09 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0004_migrate_campus_data"),
    ]

    operations = [
        # Remove old unique constraint that uses the CharField
        migrations.RemoveConstraint(
            model_name="organizationalgroup",
            name="unique_short_name_campus",
        ),
        # Remove old campus CharField index
        migrations.RemoveIndex(
            model_name="organizationalgroup",
            name="organizatio_campus_ae3223_idx",
        ),
        # Remove the old campus CharField
        migrations.RemoveField(
            model_name="organizationalgroup",
            name="campus",
        ),
        # Rename campus_id to campus
        migrations.RenameField(
            model_name="organizationalgroup",
            old_name="campus_id",
            new_name="campus",
        ),
        # Make the campus field non-nullable
        migrations.AlterField(
            model_name="organizationalgroup",
            name="campus",
            field=models.ForeignKey(
                help_text="University campus affiliation",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="organizational_group.campus",
            ),
        ),
        # Add new unique constraint with updated name
        migrations.AddConstraint(
            model_name="organizationalgroup",
            constraint=models.UniqueConstraint(
                fields=("short_name", "campus"), name="unique_short_name_campus_id"
            ),
        ),
    ]
