# Generated by Django 4.2.7 on 2025-11-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0005_finalize_campus_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Knowledge area name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the knowledge area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Area",
                "verbose_name_plural": "Knowledge Areas",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="organizatio_name_c8c06b_idx")
                ],
            },
        ),
    ]
