# Generated by Django 4.2.7 on 2025-11-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0006_knowledgearea"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationalgroup",
            name="knowledge_area_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Knowledge area foreign key (replaces CharField)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="organizational_group.knowledgearea",
            ),
        ),
    ]
