# Generated by Django 4.2.7 on 2025-11-09 11:54

from django.db import migrations


def migrate_knowledge_areas_forward(apps, schema_editor):
    """
    Migrate knowledge_area CharField values to KnowledgeArea model.
    
    This function:
    1. Extracts all unique knowledge_area values from OrganizationalGroup (case-insensitive)
    2. Creates KnowledgeArea records for each unique value
    3. Maps each OrganizationalGroup to the appropriate KnowledgeArea via knowledge_area_id FK
    4. Validates all OrganizationalGroup records have knowledge_area_id populated
    """
    OrganizationalGroup = apps.get_model('organizational_group', 'OrganizationalGroup')
    KnowledgeArea = apps.get_model('organizational_group', 'KnowledgeArea')
    
    # Dictionary to track created KnowledgeArea objects (lowercase name -> KnowledgeArea)
    knowledge_area_map = {}
    
    # Get all organizational groups
    groups = OrganizationalGroup.objects.all()
    
    # Extract unique knowledge_area values (case-insensitive)
    unique_knowledge_areas = set()
    for group in groups:
        if group.knowledge_area:
            # Store the original casing but use lowercase for deduplication
            ka_name = group.knowledge_area.strip()
            if ka_name:
                unique_knowledge_areas.add(ka_name)
    
    # Create KnowledgeArea records with case-insensitive deduplication
    for ka_name in unique_knowledge_areas:
        ka_name_lower = ka_name.lower()
        
        # Check if we've already created a KnowledgeArea for this name (case-insensitive)
        if ka_name_lower not in knowledge_area_map:
            # Check if KnowledgeArea already exists in database (case-insensitive)
            existing = KnowledgeArea.objects.filter(name__iexact=ka_name).first()
            
            if existing:
                knowledge_area_map[ka_name_lower] = existing
            else:
                # Create new KnowledgeArea with the original casing
                ka = KnowledgeArea.objects.create(
                    name=ka_name,
                    description=''
                )
                knowledge_area_map[ka_name_lower] = ka
    
    # Map each OrganizationalGroup to the appropriate KnowledgeArea
    unmapped_groups = []
    for group in groups:
        if group.knowledge_area:
            ka_name = group.knowledge_area.strip()
            if ka_name:
                ka_name_lower = ka_name.lower()
                
                # Find the corresponding KnowledgeArea
                if ka_name_lower in knowledge_area_map:
                    group.knowledge_area_id = knowledge_area_map[ka_name_lower]
                    group.save(update_fields=['knowledge_area_id'])
                else:
                    unmapped_groups.append(group.id)
            else:
                unmapped_groups.append(group.id)
        else:
            unmapped_groups.append(group.id)
    
    # Validate all OrganizationalGroup records have knowledge_area_id populated
    if unmapped_groups:
        raise ValueError(
            f"Migration failed: {len(unmapped_groups)} OrganizationalGroup record(s) "
            f"could not be mapped to a KnowledgeArea. Group IDs: {unmapped_groups[:10]}"
        )
    
    # Final validation check
    unmapped_count = OrganizationalGroup.objects.filter(knowledge_area_id__isnull=True).count()
    if unmapped_count > 0:
        raise ValueError(
            f"Migration validation failed: {unmapped_count} OrganizationalGroup record(s) "
            f"still have null knowledge_area_id after migration."
        )


def migrate_knowledge_areas_reverse(apps, schema_editor):
    """
    Reverse migration: restore CharField values from KnowledgeArea FK.
    
    This function restores the knowledge_area CharField values from the
    knowledge_area_id foreign key relationship.
    """
    OrganizationalGroup = apps.get_model('organizational_group', 'OrganizationalGroup')
    
    # Restore CharField values from FK
    groups = OrganizationalGroup.objects.select_related('knowledge_area_id').all()
    
    for group in groups:
        if group.knowledge_area_id:
            # Restore the CharField value from the FK relationship
            group.knowledge_area = group.knowledge_area_id.name
            group.save(update_fields=['knowledge_area'])


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0007_organizationalgroup_knowledge_area_id"),
    ]

    operations = [
        migrations.RunPython(
            migrate_knowledge_areas_forward,
            reverse_code=migrate_knowledge_areas_reverse
        ),
    ]
