# Generated by Django 4.2.7 on 2025-11-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0008_migrate_knowledge_area_data"),
    ]

    operations = [
        # Remove the old knowledge_area CharField index
        migrations.RemoveIndex(
            model_name="organizationalgroup",
            name="organizatio_knowled_0aafb0_idx",
        ),
        # Remove the old knowledge_area CharField
        migrations.RemoveField(
            model_name="organizationalgroup",
            name="knowledge_area",
        ),
        # Rename knowledge_area_id to knowledge_area
        migrations.RenameField(
            model_name="organizationalgroup",
            old_name="knowledge_area_id",
            new_name="knowledge_area",
        ),
        # Alter the field to make it NOT NULL (remove blank=True, null=True)
        migrations.AlterField(
            model_name="organizationalgroup",
            name="knowledge_area",
            field=models.ForeignKey(
                help_text="Knowledge area foreign key",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="organizational_group.knowledgearea",
            ),
        ),
    ]
