# Generated by Django 4.2.7 on 2025-11-09 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0009_finalize_knowledge_area_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationalgroup",
            name="knowledge_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Knowledge areas associated with this group (from related initiatives)",
                related_name="related_groups",
                to="organizational_group.knowledgearea",
            ),
        ),
        migrations.AlterField(
            model_name="organizationalgroup",
            name="knowledge_area",
            field=models.ForeignKey(
                help_text="Primary knowledge area (deprecated - use knowledge_areas)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="groups",
                to="organizational_group.knowledgearea",
            ),
        ),
    ]
