# Generated by Django 4.2.7 on 2025-11-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("initiatives", "0003_initiative_knowledge_areas"),
        ("people", "0002_alter_person_email_personemail_and_more"),
        ("organizational_group", "0010_organizationalgroup_knowledge_areas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organization name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Organization description"),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type name (e.g., Research, Extension)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Type code (e.g., research, extension)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Type description"),
                ),
            ],
            options={
                "verbose_name": "Organizational Type",
                "verbose_name_plural": "Organizational Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full organizational unit name", max_length=200
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Abbreviated organizational unit name", max_length=50
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Organizational unit website URL (optional)",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        help_text="University campus affiliation",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="organizational_group.campus",
                    ),
                ),
                (
                    "initiatives",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Initiatives associated with the organizational unit",
                        related_name="units",
                        to="initiatives.initiative",
                    ),
                ),
                (
                    "knowledge_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary knowledge area (deprecated - use knowledge_areas)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="organizational_group.knowledgearea",
                    ),
                ),
                (
                    "knowledge_areas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Knowledge areas associated with this unit (from related initiatives)",
                        related_name="related_units",
                        to="organizational_group.knowledgearea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Unit",
                "verbose_name_plural": "Organizational Units",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationalUnitLeadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Date when leadership began"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when leadership ended (null if ongoing)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this is an active leadership"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person who is a leader",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.person",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Organizational unit being led",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizational_group.organizationalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Unit Leadership",
                "verbose_name_plural": "Organizational Unit Leaderships",
                "ordering": ["-start_date"],
            },
        ),
        migrations.RemoveField(
            model_name="organizationalgroupleadership",
            name="group",
        ),
        migrations.RemoveField(
            model_name="organizationalgroupleadership",
            name="person",
        ),
        migrations.DeleteModel(
            name="OrganizationalGroup",
        ),
        migrations.DeleteModel(
            name="OrganizationalGroupLeadership",
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="leaders",
            field=models.ManyToManyField(
                help_text="People who lead the organizational unit",
                related_name="led_units",
                through="organizational_group.OrganizationalUnitLeadership",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="People who are members of the organizational unit",
                related_name="member_units",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="organization",
            field=models.ForeignKey(
                help_text="Parent organization",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="organizational_group.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationalunit",
            name="type",
            field=models.ForeignKey(
                help_text="Organizational unit type (Research, Extension, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="organizational_group.organizationaltype",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationaltype",
            index=models.Index(fields=["code"], name="organizatio_code_3f2852_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="organizatio_name_58f599_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationalunitleadership",
            index=models.Index(
                fields=["unit", "is_active"], name="organizatio_unit_id_87d775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalunitleadership",
            index=models.Index(
                fields=["person"], name="organizatio_person__948896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalunitleadership",
            index=models.Index(
                fields=["start_date"], name="organizatio_start_d_823c96_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationalunitleadership",
            constraint=models.UniqueConstraint(
                fields=("unit", "person", "start_date"),
                name="unique_unit_person_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationalunitleadership",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__gte", models.F("start_date")),
                    ("end_date__isnull", True),
                    _connector="OR",
                ),
                name="end_date_after_start_date_leadership",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalunit",
            index=models.Index(fields=["name"], name="organizatio_name_a0d926_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationalunit",
            index=models.Index(
                fields=["short_name"], name="organizatio_short_n_907f8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationalunit",
            index=models.Index(fields=["type"], name="organizatio_type_id_dcc95f_idx"),
        ),
        migrations.AddIndex(
            model_name="organizationalunit",
            index=models.Index(
                fields=["organization"], name="organizatio_organiz_1d8bda_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationalunit",
            constraint=models.UniqueConstraint(
                fields=("short_name", "organization"),
                name="unique_short_name_organization",
            ),
        ),
    ]
