# Generated by Django 4.2.7 on 2025-11-08 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitiativeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the initiative type",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the initiative type",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this initiative type"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this initiative type is active and can be used",
                    ),
                ),
            ],
            options={
                "verbose_name": "Initiative Type",
                "verbose_name_plural": "Initiative Types",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="initiatives_code_4ff6b6_idx"),
                    models.Index(
                        fields=["is_active"], name="initiatives_is_acti_264329_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                ("name", models.CharField(help_text="Initiative name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Initiative description"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Initiative start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Initiative end date (optional)",
                        null=True,
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        help_text="Person who coordinates this initiative",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinated_initiatives",
                        to="people.person",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent initiative for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="initiatives.initiative",
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        help_text="People who are team members of this initiative",
                        related_name="team_initiatives",
                        to="people.person",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Initiative type (Program, Project, Event)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="initiatives.initiativetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Initiative",
                "verbose_name_plural": "Initiatives",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="initiatives_name_f7e9f9_idx"),
                    models.Index(
                        fields=["type"], name="initiatives_type_id_04aae8_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="initiatives_start_d_5ae328_idx"
                    ),
                    models.Index(
                        fields=["coordinator"], name="initiatives_coordin_8a622e_idx"
                    ),
                    models.Index(
                        fields=["parent"], name="initiatives_parent__7769a6_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="initiative",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="end_date_after_start_date",
            ),
        ),
    ]
