# Generated by Django 4.2.7 on 2025-11-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizational_group", "0001_initial"),
        ("people", "0001_initial"),
        ("initiatives", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="knowledge_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Knowledge areas associated with this initiative",
                related_name="initiatives",
                to="organizational_group.knowledgearea",
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent initiative for hierarchical structure",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="initiatives.initiative",
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students participating in this initiative",
                related_name="student_initiatives",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="team_members",
            field=models.ManyToManyField(
                blank=True,
                help_text="People who are team members of this initiative",
                related_name="team_initiatives",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="type",
            field=models.ForeignKey(
                help_text="Initiative type (Program, Project, Event)",
                on_delete=django.db.models.deletion.PROTECT,
                to="initiatives.initiativetype",
            ),
        ),
        migrations.AddIndex(
            model_name="initiative",
            index=models.Index(fields=["name"], name="initiatives_name_f7e9f9_idx"),
        ),
        migrations.AddIndex(
            model_name="initiative",
            index=models.Index(fields=["type"], name="initiatives_type_id_04aae8_idx"),
        ),
        migrations.AddIndex(
            model_name="initiative",
            index=models.Index(
                fields=["start_date"], name="initiatives_start_d_5ae328_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="initiative",
            index=models.Index(
                fields=["coordinator"], name="initiatives_coordin_8a622e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="initiative",
            index=models.Index(
                fields=["parent"], name="initiatives_parent__7769a6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="initiative",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="end_date_after_start_date",
            ),
        ),
    ]
