# Generated by Django 4.2.7 on 2025-11-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
        ("initiatives", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Students participating in this initiative",
                related_name="student_initiatives",
                to="people.person",
            ),
        ),
    ]
