# Generated by Django 4.2.7 on 2025-11-15 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0001_initial"),
        ("initiatives", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                help_text="Campus where this initiative is performed",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiatives",
                to="organizational_group.campus",
            ),
        ),
        migrations.AddIndex(
            model_name="initiative",
            index=models.Index(
                fields=["campus"], name="initiatives_campus__9f90e3_idx"
            ),
        ),
    ]
