# Generated by Django 4.2.7 on 2025-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0009_finalize_knowledge_area_model"),
        ("initiatives", "0002_initiative_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="knowledge_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Knowledge areas associated with this initiative",
                related_name="initiatives",
                to="organizational_group.knowledgearea",
            ),
        ),
    ]
