# Generated by Django 4.2.7 on 2025-11-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0001_initial"),
        ("initiatives", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="demanding_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that demands/requests this initiative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demanded_initiatives",
                to="organizational_group.organizationalunit",
            ),
        ),
    ]
