# Generated by Django 4.2.7 on 2025-11-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizational_group", "0001_initial"),
        ("initiatives", "0004_change_demanding_partner_to_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="partnerships",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organizational units that are partners in this initiative",
                related_name="partnership_initiatives",
                to="organizational_group.organizationalunit",
            ),
        ),
    ]
