# Generated by Django 4.2.7 on 2025-11-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
        ("initiatives", "0004_failedinitiativeimport"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitiativeCoordinatorChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the change occurred"
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True, help_text="Reason for the coordinator change"
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        default="System",
                        help_text="Who made the change (username or 'CSV Import', 'System', etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        help_text="The initiative whose coordinator changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinator_changes",
                        to="initiatives.initiative",
                    ),
                ),
                (
                    "new_coordinator",
                    models.ForeignKey(
                        help_text="The new coordinator",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="newly_coordinated_initiatives",
                        to="people.person",
                    ),
                ),
                (
                    "previous_coordinator",
                    models.ForeignKey(
                        help_text="The previous coordinator",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="previous_coordinated_initiatives",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Initiative Coordinator Change",
                "verbose_name_plural": "Initiative Coordinator Changes",
                "ordering": ["-change_date"],
                "indexes": [
                    models.Index(
                        fields=["initiative"], name="initiatives_initiat_d4cdf5_idx"
                    ),
                    models.Index(
                        fields=["change_date"], name="initiatives_change__dbd238_idx"
                    ),
                    models.Index(
                        fields=["previous_coordinator"],
                        name="initiatives_previou_c57200_idx",
                    ),
                    models.Index(
                        fields=["new_coordinator"],
                        name="initiatives_new_coo_f83468_idx",
                    ),
                ],
            },
        ),
    ]
