# Generated by Django 4.2.7 on 2025-11-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Person's full name", max_length=200),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Person's primary email address (optional)",
                        max_length=254,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PersonEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address (must be unique across all people)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary email for this person",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person this email belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="people.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person Email",
                "verbose_name_plural": "Person Emails",
                "ordering": ["-is_primary", "email"],
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["email"], name="people_pers_email_52ffb2_idx"),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["name"], name="people_pers_name_3035d1_idx"),
        ),
        migrations.AddIndex(
            model_name="personemail",
            index=models.Index(fields=["email"], name="people_pers_email_664b97_idx"),
        ),
        migrations.AddIndex(
            model_name="personemail",
            index=models.Index(
                fields=["person", "is_primary"], name="people_pers_person__7bb64e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personemail",
            constraint=models.UniqueConstraint(
                fields=("person", "email"), name="unique_person_email"
            ),
        ),
    ]
