# Generated by Django 4.2.7 on 2025-11-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedScholarshipImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(help_text="Row number in the CSV file"),
                ),
                (
                    "error_reason",
                    models.TextField(help_text="Reason why the import failed"),
                ),
                ("raw_data", models.JSONField(help_text="Raw CSV row data as JSON")),
                (
                    "import_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the import was attempted"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Whether the issue has been resolved"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Notes about how the issue was resolved"
                    ),
                ),
            ],
            options={
                "verbose_name": "Failed Scholarship Import",
                "verbose_name_plural": "Failed Scholarship Imports",
                "ordering": ["-import_date", "row_number"],
                "indexes": [
                    models.Index(
                        fields=["import_date"], name="scholarship_import__c574b7_idx"
                    ),
                    models.Index(
                        fields=["resolved"], name="scholarship_resolve_305c13_idx"
                    ),
                    models.Index(
                        fields=["row_number"], name="scholarship_row_num_d80f25_idx"
                    ),
                ],
            },
        ),
    ]
