# Generated by Django 4.2.7 on 2025-11-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScholarshipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the scholarship type",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the scholarship type",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the scholarship type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this scholarship type is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scholarship Type",
                "verbose_name_plural": "Scholarship Types",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="scholarship_code_702380_idx"),
                    models.Index(
                        fields=["is_active"], name="scholarship_is_acti_7aa69e_idx"
                    ),
                ],
            },
        ),
    ]
