# Generated by Django 4.2.7 on 2025-11-11 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("initiatives", "0005_add_partnerships"),
        ("people", "0001_initial"),
        ("organizational_group", "0001_initial"),
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive name for the scholarship", max_length=300
                    ),
                ),
                ("start_date", models.DateField(help_text="Scholarship start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Scholarship end date (optional)",
                        null=True,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly scholarship value in BRL",
                        max_digits=10,
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        help_text="Campus where scholarship is executed",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scholarships",
                        to="organizational_group.campus",
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related initiative/project (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scholarships",
                        to="initiatives.initiative",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization sponsoring the scholarship (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_scholarships",
                        to="organizational_group.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Person receiving the scholarship",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_scholarships",
                        to="people.person",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        help_text="Person supervising the scholarship",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supervised_scholarships",
                        to="people.person",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Type of scholarship",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scholarships",
                        to="scholarships.scholarshiptype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scholarship",
                "verbose_name_plural": "Scholarships",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["title"], name="scholarship_title_ca36b3_idx"),
                    models.Index(
                        fields=["campus"], name="scholarship_campus__6e1b06_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="scholarship_start_d_12b391_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="scholarship_end_dat_a4c04d_idx"
                    ),
                    models.Index(
                        fields=["student"], name="scholarship_student_a1e338_idx"
                    ),
                    models.Index(
                        fields=["supervisor"], name="scholarship_supervi_265952_idx"
                    ),
                    models.Index(
                        fields=["type"], name="scholarship_type_id_77a732_idx"
                    ),
                    models.Index(
                        fields=["initiative"], name="scholarship_initiat_97238e_idx"
                    ),
                    models.Index(
                        fields=["sponsor"], name="scholarship_sponsor_1eec1d_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="scholarship",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__gte", models.F("start_date")),
                    ("end_date__isnull", True),
                    _connector="OR",
                ),
                name="scholarship_end_date_after_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarship",
            constraint=models.CheckConstraint(
                check=models.Q(("value__gt", 0)), name="scholarship_value_positive"
            ),
        ),
    ]
